### ISSUE TITLE
pyasn1.type cannot import Opentype

### ISSUE THREAD

**Issue by ojarosch** [coruus/pyasn1-modules#2]
Recently I discovered PyDrive a tool to use GDrive within a Python app.
Upon deploying my script on a remote Debian Server i recieved following Stacktrace.
As I am a newbie to python, I don't know how to resolve this problem.

I used `Python 2.7.9`

```
Traceback (most recent call last):
  File "/root/test.py", line 9, in <module>
    from pydrive.auth import GoogleAuth
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 9, in <module>
    from oauth2client.service_account import ServiceAccountCredentials
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/service_account.py", line 26, in <module>
    from oauth2client import crypt
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/crypt.py", line 23, in <module>
    from oauth2client import _pure_python_crypt
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_pure_python_crypt.py", line 24, in <module>
    from pyasn1_modules.rfc2459 import Certificate
  File "/usr/local/lib/python2.7/dist-packages/pyasn1_modules/rfc2459.py", line 20, in <module>
    from pyasn1.type import opentype
ImportError: cannot import name opentype
```

Specifically the last 2 lines lead me here

```
from pyasn1.type import opentype
ImportError: cannot import name opentype
```

**Comment by ojarosch** [comment]
reinstalling `pyasn1_modules` manually via pip did it for me
